services:  
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - kafka_net

networks:
  kafka_net:
    external: true
    name: kafka_shared_network